name: Create Release Tag
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  get-version:
    name: Get version number
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, '# RELEASE v') || github.event_name == 'workflow_dispatch'

    steps:
      - uses: actions/checkout@v3
      - name: Parse version
        run: |
          echo "VERSION=$(sed -En "s/('version' => ){1}'(.*)',$/\2/gp" src/version.txt)" >> $GITHUB_ENV

      - name: Create tag
        run: |
          git tag v${{ env.VERSION }}
          git push origin v${{ env.VERSION }}

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.VERSION }}
          generateReleaseNotes: true
